# Rate limiting (defaults to disabled)
# Limits item clicks to rateLimit per rateLimitTime.
# Example below for limiting to 100 item clicks or drops per 60 seconds.
#
# rateLimit: 100
# rateLimitTime: 60

# Custom blacklists
#
# You can name these whatever you want, a permission with the appropriate name
# will be created automatically.
#
# The lists below serve only as an example, feel free to rename, remove or
# add lists according to your server's needs.
blacklist:
        basic:
                items:
                        - 'minecraft:barrier'
                        - 'minecraft:water_bucket'
                        - 'minecraft:flint_and_steel'
                        - 'minecraft:monster_egg'
        spawner:
                items:
                        - 'minecraft:mob_spawner'
                        - 'minecraft:spawn_egg'
        limited:
                items:
                        - 'minecraft:lava_bucket'
                        - 'minecraft:tnt'
                        - 'minecraft:tnt_minecart'

# Whitelist - items to allow arbitrary nbt on.
# Enchanted items may not be safe e.g. looting 32000.
whitelist:
        - 'minecraft:skull'
        - 'minecraft:banner'
        - 'minecraft:bow'
        - 'minecraft:iron_sword'
        - 'minecraft:wooden_sword'
        - 'minecraft:stone_sword'
        - 'minecraft:diamond_sword'
        - 'minecraft:golden_sword'
        - 'minecraft:leather_helmet'
        - 'minecraft:leather_chestplate'
        - 'minecraft:leather_leggings'
        - 'minecraft:leather_boots'
        - 'minecraft:chainmail_helmet'
        - 'minecraft:chainmail_chestplate'
        - 'minecraft:chainmail_leggings'
        - 'minecraft:chainmail_boots'
        - 'minecraft:iron_helmet'
        - 'minecraft:iron_chestplate'
        - 'minecraft:iron_leggings'
        - 'minecraft:iron_boots'
        - 'minecraft:diamond_helmet'
        - 'minecraft:diamond_chestplate'
        - 'minecraft:diamond_leggings'
        - 'minecraft:diamond_boots'
        - 'minecraft:golden_helmet'
        - 'minecraft:golden_chestplate'
        - 'minecraft:golden_leggings'
        - 'minecraft:golden_boots'

# In strings
# %1$s - player name.
# %2$s - item name.
# %3$s - full item nbt.
# Note: you can limit the length of the strings with the following:
# %3$.80s - full item nbt (limited to 80 characters).

# Action when a player spawns an item not in the creative menu.
unavailable:
# Optional, defaults to true
#        block: true

# Optional, if not set, no message is sent.
        message: 'You do not have permission for %2$s.'

# Optional, defaults to bukkit.broadcast.admin
#        broadcastPermission: bukkit.broadcast.admin

# Optional, if not set, no broadcast is sent.
        broadcastMessage: '%1$s attempted to spawn in %3$s'

# List of commands, to run.
#        commands: 
#                - 'kick %1$s You do not have permission for %2$s.'

# Action when a player spawns an item in the creative menu they have no permission for.
# Any of the values from the unavailable action can be set here.
nopermission:
        message: 'You do not have permission for %2$s.'

# Action when a player spawns an item which is blacklisted.
# Any of the values from the unavailable action can be set here.
blacklisted:
        message: 'You do not have permission for %2$s.'

# Action when a player exceeds the item click/drop rate limit
# Note: this check is performed first
# This might be extremely spammy for admins.
onRateLimit:
        broadcastMessage: '%1$s exceeded rate limit for inventory clicks'
        message: 'Do not click so fast!'